2012/02/22 19:26:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cool".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('cool')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('cool')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/cool')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/cool
2012/02/22 19:30:59 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 19:34:59 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 19:35:46 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/%27carlos%27
2012/02/22 19:36:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 19:36:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cool".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('cool')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('cool')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/cool')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/cool
2012/02/22 19:47:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 19:48:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php:259
Stack trace:
#0 C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php(83): EmpleadoController->loadModel('1')
#1 [internal function]: EmpleadoController->actionView('1')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CAction.php(104): ReflectionMethod->invokeArgs(Object(EmpleadoController), Array)
#3 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CInlineAction.php(48): CAction->runWithParamsInternal(Object(EmpleadoController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#11 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#13 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view')
#14 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/1
2012/02/22 19:48:10 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/c...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/carlos
2012/02/22 19:48:15 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/'...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/'carlos'
2012/02/22 19:48:22 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 19:48:25 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/'...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/'carlos'
2012/02/22 19:48:25 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/c...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/carlos
2012/02/22 19:48:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php:259
Stack trace:
#0 C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php(83): EmpleadoController->loadModel('1')
#1 [internal function]: EmpleadoController->actionView('1')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CAction.php(104): ReflectionMethod->invokeArgs(Object(EmpleadoController), Array)
#3 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CInlineAction.php(48): CAction->runWithParamsInternal(Object(EmpleadoController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#11 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#13 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view')
#14 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/1
2012/02/22 19:48:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 19:48:57 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/cool
2012/02/22 19:49:02 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 19:49:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/id/carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('view/id/carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/dcv8/DCV/index.php/view/id/carlos
2012/02/22 19:51:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "id=carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('id=carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('id=carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/id=car...')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/id%3Dcarlos
2012/02/22 19:51:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "id=carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('id=carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('id=carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/id=car...')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/id%3Dcarlos
2012/02/22 19:53:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 19:53:34 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/i...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/id=carlos
2012/02/22 19:53:42 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/view/c...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/view/carlos
2012/02/22 19:53:48 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 19:54:02 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/id='carlos'
2012/02/22 19:55:06 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:328
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#9 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update...')
#10 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/carlos
2012/02/22 20:03:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php:259
Stack trace:
#0 C:\xampp\htdocs\dcv8\DCV\protected\controllers\EmpleadoController.php(121): EmpleadoController->loadModel('1')
#1 [internal function]: EmpleadoController->actionUpdate('1')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CAction.php(104): ReflectionMethod->invokeArgs(Object(EmpleadoController), Array)
#3 C:\xampp\htdocs\dcv8\yii\framework\web\actions\CInlineAction.php(48): CAction->runWithParamsInternal(Object(EmpleadoController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#11 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('update')
#13 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/update')
#14 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/update/1
2012/02/22 20:05:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 20:12:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 20:14:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loadModel".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('loadModel')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('loadModel')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/loadMo...')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/loadModel
2012/02/22 20:14:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "carlos".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('carlos')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('carlos')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('empleado/carlos')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/empleado/carlos
2012/02/22 20:39:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('')
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno')
#9 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno
2012/02/22 21:25:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('')
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno')
#9 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno
2012/02/22 21:25:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "update/view".' in C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('update/view')
#1 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/dcv8/DCV/index.php/update/100666
2012/02/22 21:27:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "100666".' in C:\xampp\htdocs\dcv8\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(262): CController->missingAction('100666')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('100666')
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno/100666/u...')
#3 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno/100666/update
2012/02/23 19:14:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('create')
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno/create')
#9 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno/create
2012/02/23 19:14:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('')
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno')
#9 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno/
2012/02/24 19:47:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\dcv8\yii\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\dcv8\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\dcv8\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(277): CController->run('')
#8 C:\xampp\htdocs\dcv8\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('alumno')
#9 C:\xampp\htdocs\dcv8\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\dcv8\DCV\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/dcv8/DCV/index.php/alumno/
